# ***Example***

In [ ]:
import numpy as np
import random
from timeit import timeit

#define addtion function
def add_python(z1,z2):
  return [z1+z2 for z1,z2 in zip(z1,z2)]
def add_numpy(z1,z2):
  return np.numpy(z1,z2)

#generate random sample data
z1 = random.sample(range(1000),100)
z2 = random.sample(range(1000),100)

#time the exexution of each function
python_time = timeit("add_python(z1,z2)",globals=globals(),number=1000)
numpy_time = timeit("add_python(z1,z2)",globals=globals(),number=1000)

#print result
print(f"Pure python addition :{python_time:.2f} s per loop")
print(f"Numpy python addition :{numpy_time:.2f} s per loop")

Pure python addition :0.03 s per loop
Numpy python addition :0.02 s per loop


In [ ]:
import numpy as np
import random
from timeit import timeit

#define addtion function
def add_python(z1,z2):
  return [z1+z2 for z1,z2 in zip(z1,z2)]
def add_numpy(z1,z2):
  return np.numpy(z1,z2)

#generate random sample data
size = 100000 #increase size for more pronounced difference
z1_list = random.sample(range(size+1),size)
z2_list = random.sample(range(size+1),size)
z1_np=np.array(z1_list)
z2_np=np.array(z2_list)

#time the exexution of each function
python_time = timeit("add_python(z1_list,z2_list)",globals=globals(),number=100)
numpy_time = timeit("add_python(z1_np,z2_np)",globals=globals(),number=100)

#print result
print(f"Pure python addition :{python_time:.2f} s per loop")
print(f"Numpy python addition :{numpy_time:.2f} s per loop")

Pure python addition :2.21 s per loop
Numpy python addition :1.94 s per loop


In [ ]:
import numpy as np
#create and display zero and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1,2,3])
n_dim_array = np.array([[1,2],[3,4]])

for arr in [zero_dim_array,one_dim_array,n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type:{arr.dtype}\n")

Array:
5
Dimension: 0
Data type:int64

Array:
[1 2 3]
Dimension: 1
Data type:int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type:int64



In [ ]:
#initilialize an all zero array with size 2x3
zero_arr=np.zeros((2,3))
print("A zero array is \n",zero_arr,"with dimensions",zero_arr.shape,"\n")

A zero array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [ ]:
array_0d=np.array(5)
array_1d=np.array([1,2,3,4,5])
array_2d=np.array([[1,2,3],[4,5,6]])
array_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

#print array with shapes
for i,arr in enumerate([array_0d,array_1d,array_2d,array_3d]):
  print(f"{i}D Array: \n{arr}\nShape:{arr.shape}\n")

0D Array: 
5
Shape:()

1D Array: 
[1 2 3 4 5]
Shape:(5,)

2D Array: 
[[1 2 3]
 [4 5 6]]
Shape:(2, 3)

3D Array: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape:(2, 2, 2)



In [ ]:
import numpy as np
array = np . array ([[1 , 2 , 3] , [4 , 5 , 6]]) # Shape (2 , 3)
reshaped_array = array . reshape (3 , 2) # Reshape to (3 ,2) , keeping 6 elements
print (" Original Shape :", array . shape , "\nReshaped Shape :", reshaped_array . shape )

 Original Shape : (2, 3) 
Reshaped Shape : (3, 2)


In [ ]:
import numpy as np
a = np . arange (1 , 10)
print ( a )
x = range (1 , 10)
print ( x ) # x is an iterator
print ( list ( x ) )
# further arange examples :
x = np . arange (10.4)
print ( x )
x = np . arange (0.5 , 10.4 , 0.8)
print ( x )

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
import numpy as np
# 50 values between 1 and 10:
print ( np . linspace (1 , 10,10,endpoint=True,retstep=True) )
# 7 values between 1 and 10:
print ( np . linspace (1 , 10 , 7) )
# excluding the endpoint :
print ( np . linspace (1 , 10 , 7 , endpoint = False ) )

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [ ]:
import numpy as np
# Create arrays of specified shapes
ones_array = np . ones ((2 , 3) ) # Shape : (2 , 3)
zeros_array = np . zeros ((3 , 2) ) # Shape : (3 , 2)
empty_array = np . empty ((2 , 2) ) # Shape : (2 , 2)
identity_matrix = np . eye (3) # Shape : (3 , 3)
print ( ones_array , zeros_array , empty_array ,identity_matrix , sep ="\n\n")

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
array_from_list = np . array ([1 , 2 , 3]) # [1 2 3]
array_from_tuple = np . array ((4 , 5 , 6)) # [4 5 6]
array_from_nested_list = np . array ([[1 , 2 , 3] , [4 , 5 ,6]]) # [[1 2 3] [4 5 6]]
print ( array_from_list , array_from_tuple ,array_from_nested_list , sep ="\n")

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
array = np . array ([1 , 2 , 3])
print(array)
# Multiplies each element by 2 , result : [2 , 4 , 6]
new_array = array * 2
print(new_array)
# Creates a new array with the same elements
copied_array = np . copy ( array )
print(copied_array)
# Slices elements from index 1 to 3 , result :[2]
sliced_array = array [1:2]
print(sliced_array)

[1 2 3]
[2 4 6]
[1 2 3]
[2]


In [ ]:
import numpy as np
# Existing Array of Shape :(2 ,3)
arr = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
# Creating Array with Shape of existing array :
zeros , ones , empty = np . zeros ( arr . shape ) , np . ones (arr . shape ) , np . empty ( arr . shape ) # Shape : (2 ,3)
print ( arr , zeros , ones , empty , sep ='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4.82802312e-310 0.00000000e+000 3.35559136e-143]
 [9.30350598e+199 4.24941018e-086 1.55535091e+161]]


In [ ]:
import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
# Stacking examples
hstacked = np . hstack (( arr1 , arr2 ) )
# Output hstack : [[1 2 5 6] [3 4 7 8]]
vstacked = np . vstack (( arr1 , arr2 ) )
# Output vstack [[1 2] [3 4] [5 6] [7 8]]
colstacked = np . column_stack (( arr1 [0] , arr2 [0]) )
# Output column stack : [[1 5] [2 6]]
print ( hstacked , vstacked , colstacked , sep ='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [ ]:
import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
concat_axis0 = np . concatenate (( arr1 , arr2 ) , axis =0)
# Concatenate along axis 0 ( vertical ) Shape : (4 , 2)
concat_axis1 = np . concatenate (( arr1 , arr2 ) , axis =1)
# Concatenate along axis 1 ( horizontal ) Shape : (2 , 4)
print ( concat_axis0 , concat_axis1 , sep ='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# ***Workshop-1***

# **TO-DO TASK**

In [ ]:
#Questions of task 4 problem 1

import numpy as np

#Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n",empty_array)

#Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n",ones_array)

#Return a new array of given shape and type, filled with fill value
shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\nFilled Array (3x3) with value 7:\n",filled_array)

#Return a new array of zeros with same shape and type as a given array
existing_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(existing_array)
print("\nZeros Like Array :\n",zeros_array)

#Return a new array of ones with same shape and type as a given array
ones_array = np.ones_like(existing_array)
print("\nOnes Like Array \n",ones_array)

# For an existing list new_list = [1, 2, 3, 4] convert to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumPy Array from List:\n",numpy_array)

Empty Array (2x2):
 [[4.68327637e-310 0.00000000e+000]
 [6.55441302e-310 1.48219694e-323]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array (3x3) with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array :
 [[0 0]
 [0 0]]

Ones Like Array 
 [[1 1]
 [1 1]]

NumPy Array from List:
 [1 2 3 4]


In [ ]:
#question of task 4 problem 2
import numpy as np

#Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:",arr1)

#Create a 3X3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values ranging from 0 to 8:",arr2)

#Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:",identity_matrix)

#Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30 and its Mean:",random_array)
print("Mean of the array:", mean_value)

#Create a 10X10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:",random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

#Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced with 1:",zero_array)

#Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr3 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr3[::-1]
print("\nReversed Array:",reversed_arr)

#Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:",border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:",checkerboard)

Array with values ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values ranging from 0 to 8: [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30 and its Mean: [0.51372394 0.64918427 0.31200882 0.38708149 0.7580962  0.30895274
 0.35444972 0.65519916 0.35437324 0.35760477 0.10497297 0.32162912
 0.15104056 0.23491178 0.54352017 0.94912703 0.81025278 0.56519107
 0.29716563 0.41884361 0.14335065 0.40805832 0.47314736 0.44055325
 0.09925766 0.15425698 0.16133892 0.63617832 0.76216584 0.2769246 ]
Mean of the array: 0.4200853658636378

10x10 Random Array: [[0.19854604 0.79289405 0.3929793  0.16728623 0.69982393 0.57891945
  0.31859554 0.72396383 0.20204921 0.2195354 ]
 [0.61741366 0.56544188 0.65287504 0.84408662 0.53242538 0.98938327
  0.6594422  0.70366795 0.5262129  0.86758916]
 [0.74241973 0.27349754 0.85954303 0.393

In [ ]:
#questions of task 4 problem 3
import numpy as np

#given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#Add the two arrays
addition = x+y
print("Addition of x and y:",addition)

#Subtract the two arrays
subtraction = x-y
print("\nSubtraction of x and y:",subtraction)

#Multiply the array with any integers of your choice
multiplied_x = x * 2
print("\nMultiplying x by 2:",multiplied_x)

#Find the square of each element of the array
squared_x = np.square(x)
print("\nSquare of each element of x:",squared_x)

#Find the dot product between: v and w; x and v; x and y
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("\nDot product of v and w:", dot_v_w)
print("Dot product of x and v:",dot_x_v)
print("Dot product of x and y:",dot_x_y)

#Concatenate x and y along row and concatenate v and w along column
concat_x_y_row = np.concatenate((x, y), axis=0)
concat_v_w_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("\nConcatenating x and y along rows:",concat_x_y_row)
print("\nConcatenating v and w along columns:",concat_v_w_column)

# 7. Concatenate x and v; if you get an error, observe and explain why did you get the error?
concat_x_v = np.concatenate((x, v), axis=0)
print("\nConcatenating x and v along rows:",concat_x_v)

    #the output will be error because both x and v must have same demension but x has 2 rows while v has 1 so concatinate cannot be performed.

Addition of x and y: [[ 6  8]
 [10 13]]

Subtraction of x and y: [[-4 -4]
 [-4 -3]]

Multiplying x by 2: [[ 2  4]
 [ 6 10]]

Square of each element of x: [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]

Concatenating x and y along rows: [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v and w along columns: [[ 9 11]
 [10 12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#question of task 4 problem 4
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.eye(2)
result = np.dot(A, A_inv)
print("Result: ",result)
print("\nIs A * A^-1 equal to the identity matrix? ", np.allclose(result, I))

#AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB (A * B):")
print(AB)
print("\nBA (B * A):")
print(BA)
print("\nIs AB equal to BA? ", np.array_equal(AB, BA))

#Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
B_T_A_T = np.dot(B_T, A_T)

print("\n(AB)^T (Transpose of AB):")
print(AB_T)
print("\nB^T * A^T:")
print(B_T_A_T)
print("\nIs (AB)^T equal to B^T * A^T? ", np.array_equal(AB_T, B_T_A_T))

# Solving the system of linear equations using inverse method
# The system of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

# Solving for X using the inverse method
A_inv_matrix = np.linalg.inv(A_matrix)
X = np.dot(A_inv_matrix, B_matrix)
print("\nSolution of the system of linear equations (using inverse method):")
print(X)



Result:  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A^-1 equal to the identity matrix?  True

AB (A * B):
[[23 13]
 [51 29]]

BA (B * A):
[[36 44]
 [13 16]]

Is AB equal to BA?  False

(AB)^T (Transpose of AB):
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T?  True

Solution of the system of linear equations (using inverse method):
[ 2.  1. -2.]


In [ ]:
#using np.lang.inv()
import numpy as np
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

A_inv_matrix = np.linalg.inv(A_matrix)
X = np.dot(A_inv_matrix, B_matrix)
print("\nSolution of the system of linear equations (using np.linalg.inv method):")
print(X)



Solution of the system of linear equations (using np.linalg.inv method):
[ 2.  1. -2.]


In [ ]:
#experiment task :4.2
import numpy as np
import time

#Element-wise Addition
#Python Lists
size = 1000000
list1 = list(range(size))
list2 = list(range(size, 2 * size))
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Python List - Element-wise Addition Time: {end_time - start_time:.6f} seconds")
#NumPy Arrays
np_list1 = np.arange(size)
np_list2 = np.arange(size, 2 * size)

start_time = time.time()
np_addition = np_list1 + np_list2
end_time = time.time()
print(f"NumPy Array - Element-wise Addition Time: {end_time - start_time:.6f} seconds")

#Element-wise Multiplication
#Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Python List - Element-wise Multiplication Time: {end_time - start_time:.6f} seconds")
#NumPy Arrays
start_time = time.time()
np_multiplication = np_list1 * np_list2
end_time = time.time()
print(f"NumPy Array - Element-wise Multiplication Time: {end_time - start_time:.6f} seconds")

#Dot Product
#Python Lists
start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(size)])
end_time = time.time()
print(f"Python List - Dot Product Time: {end_time - start_time:.6f} seconds")
#NumPy Arrays
start_time = time.time()
dot_product_np = np.dot(np_list1, np_list2)
end_time = time.time()
print(f"NumPy Array - Dot Product Time: {end_time - start_time:.6f} seconds")

#Matrix Multiplication
# Python Lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
matrix_multiplication_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(100)) for j in range(100)]for i in range(100)]
#Matrix multiplication
end_time = time.time()
print(f"Python List - Matrix Multiplication Time: {end_time - start_time:.6f} seconds")

#NumPy Arrays
np_matrix1 = np.random.rand(100, 100)
np_matrix2 = np.random.rand(100, 100)

start_time = time.time()
matrix_multiplication_np = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print(f"NumPy Array - Matrix Multiplication Time: {end_time - start_time:.6f} seconds")


Python List - Element-wise Addition Time: 0.187964 seconds
NumPy Array - Element-wise Addition Time: 0.004273 seconds
Python List - Element-wise Multiplication Time: 0.145509 seconds
NumPy Array - Element-wise Multiplication Time: 0.005109 seconds
Python List - Dot Product Time: 0.180380 seconds
NumPy Array - Dot Product Time: 0.001959 seconds
Python List - Matrix Multiplication Time: 0.182047 seconds
NumPy Array - Matrix Multiplication Time: 0.000308 seconds
